/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MyAgreementsRouteImport } from './routes/my-agreements'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as MyComplaintsRouteImport } from './routes/my-complaints'
import { Route as MyInquiriesRouteImport } from './routes/my-inquiries'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as ChatsConversationIdRouteImport } from './routes/chats.$conversationId'
import { Route as HostelIdRouteImport } from './routes/hostel.$id'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAgreementsRouteImport } from './routes/owner.agreements'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerChatsRouteImport } from './routes/owner.chats'
import { Route as OwnerComplaintsRouteImport } from './routes/owner.complaints'
import { Route as OwnerHostelsRouteImport } from './routes/owner.hostels'
import { Route as OwnerInquiriesRouteImport } from './routes/owner.inquiries'
import { Route as OwnerVerificationRouteImport } from './routes/owner.verification'
import { Route as OwnerChatsConversationIdRouteImport } from './routes/owner.chats.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAgreementsRoute = MyAgreementsRouteImport.update({
  id: '/my-agreements',
  path: '/my-agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyComplaintsRoute = MyComplaintsRouteImport.update({
  id: '/my-complaints',
  path: '/my-complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInquiriesRoute = MyInquiriesRouteImport.update({
  id: '/my-inquiries',
  path: '/my-inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatsRoute,
} as any)
const HostelIdRoute = HostelIdRouteImport.update({
  id: '/hostel/$id',
  path: '/hostel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAgreementsRoute = OwnerAgreementsRouteImport.update({
  id: '/owner/agreements',
  path: '/owner/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/owner/analytics',
  path: '/owner/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerChatsRoute = OwnerChatsRouteImport.update({
  id: '/owner/chats',
  path: '/owner/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerComplaintsRoute = OwnerComplaintsRouteImport.update({
  id: '/owner/complaints',
  path: '/owner/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerHostelsRoute = OwnerHostelsRouteImport.update({
  id: '/owner/hostels',
  path: '/owner/hostels',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerInquiriesRoute = OwnerInquiriesRouteImport.update({
  id: '/owner/inquiries',
  path: '/owner/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVerificationRoute = OwnerVerificationRouteImport.update({
  id: '/owner/verification',
  path: '/owner/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerChatsConversationIdRoute =
  OwnerChatsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => OwnerChatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chats': typeof ChatsRouteWithChildren
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-agreements': typeof MyAgreementsRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/my-inquiries': typeof MyInquiriesRoute
  '/notifications': typeof NotificationsRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/signup': typeof SignupRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/hostel/$id': typeof HostelIdRoute
  '/owner/agreements': typeof OwnerAgreementsRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/chats': typeof OwnerChatsRouteWithChildren
  '/owner/complaints': typeof OwnerComplaintsRoute
  '/owner/hostels': typeof OwnerHostelsRoute
  '/owner/inquiries': typeof OwnerInquiriesRoute
  '/owner/verification': typeof OwnerVerificationRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/chats/$conversationId': typeof OwnerChatsConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chats': typeof ChatsRouteWithChildren
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-agreements': typeof MyAgreementsRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/my-inquiries': typeof MyInquiriesRoute
  '/notifications': typeof NotificationsRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/signup': typeof SignupRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/hostel/$id': typeof HostelIdRoute
  '/owner/agreements': typeof OwnerAgreementsRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/chats': typeof OwnerChatsRouteWithChildren
  '/owner/complaints': typeof OwnerComplaintsRoute
  '/owner/hostels': typeof OwnerHostelsRoute
  '/owner/inquiries': typeof OwnerInquiriesRoute
  '/owner/verification': typeof OwnerVerificationRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/chats/$conversationId': typeof OwnerChatsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chats': typeof ChatsRouteWithChildren
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-agreements': typeof MyAgreementsRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/my-inquiries': typeof MyInquiriesRoute
  '/notifications': typeof NotificationsRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/signup': typeof SignupRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/hostel/$id': typeof HostelIdRoute
  '/owner/agreements': typeof OwnerAgreementsRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/chats': typeof OwnerChatsRouteWithChildren
  '/owner/complaints': typeof OwnerComplaintsRoute
  '/owner/hostels': typeof OwnerHostelsRoute
  '/owner/inquiries': typeof OwnerInquiriesRoute
  '/owner/verification': typeof OwnerVerificationRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/chats/$conversationId': typeof OwnerChatsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/chats'
    | '/compare'
    | '/favorites'
    | '/login'
    | '/map'
    | '/my-agreements'
    | '/my-bookings'
    | '/my-complaints'
    | '/my-inquiries'
    | '/notifications'
    | '/preferences'
    | '/profile'
    | '/recommendations'
    | '/signup'
    | '/admin/verification'
    | '/chats/$conversationId'
    | '/hostel/$id'
    | '/owner/agreements'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/chats'
    | '/owner/complaints'
    | '/owner/hostels'
    | '/owner/inquiries'
    | '/owner/verification'
    | '/owner/'
    | '/owner/chats/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/chats'
    | '/compare'
    | '/favorites'
    | '/login'
    | '/map'
    | '/my-agreements'
    | '/my-bookings'
    | '/my-complaints'
    | '/my-inquiries'
    | '/notifications'
    | '/preferences'
    | '/profile'
    | '/recommendations'
    | '/signup'
    | '/admin/verification'
    | '/chats/$conversationId'
    | '/hostel/$id'
    | '/owner/agreements'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/chats'
    | '/owner/complaints'
    | '/owner/hostels'
    | '/owner/inquiries'
    | '/owner/verification'
    | '/owner'
    | '/owner/chats/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/chats'
    | '/compare'
    | '/favorites'
    | '/login'
    | '/map'
    | '/my-agreements'
    | '/my-bookings'
    | '/my-complaints'
    | '/my-inquiries'
    | '/notifications'
    | '/preferences'
    | '/profile'
    | '/recommendations'
    | '/signup'
    | '/admin/verification'
    | '/chats/$conversationId'
    | '/hostel/$id'
    | '/owner/agreements'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/chats'
    | '/owner/complaints'
    | '/owner/hostels'
    | '/owner/inquiries'
    | '/owner/verification'
    | '/owner/'
    | '/owner/chats/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MyAgreementsRoute: typeof MyAgreementsRoute
  MyBookingsRoute: typeof MyBookingsRoute
  MyComplaintsRoute: typeof MyComplaintsRoute
  MyInquiriesRoute: typeof MyInquiriesRoute
  NotificationsRoute: typeof NotificationsRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SignupRoute: typeof SignupRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  HostelIdRoute: typeof HostelIdRoute
  OwnerAgreementsRoute: typeof OwnerAgreementsRoute
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerChatsRoute: typeof OwnerChatsRouteWithChildren
  OwnerComplaintsRoute: typeof OwnerComplaintsRoute
  OwnerHostelsRoute: typeof OwnerHostelsRoute
  OwnerInquiriesRoute: typeof OwnerInquiriesRoute
  OwnerVerificationRoute: typeof OwnerVerificationRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-agreements': {
      id: '/my-agreements'
      path: '/my-agreements'
      fullPath: '/my-agreements'
      preLoaderRoute: typeof MyAgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-complaints': {
      id: '/my-complaints'
      path: '/my-complaints'
      fullPath: '/my-complaints'
      preLoaderRoute: typeof MyComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-inquiries': {
      id: '/my-inquiries'
      path: '/my-inquiries'
      fullPath: '/my-inquiries'
      preLoaderRoute: typeof MyInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$conversationId': {
      id: '/chats/$conversationId'
      path: '/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/hostel/$id': {
      id: '/hostel/$id'
      path: '/hostel/$id'
      fullPath: '/hostel/$id'
      preLoaderRoute: typeof HostelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/agreements': {
      id: '/owner/agreements'
      path: '/owner/agreements'
      fullPath: '/owner/agreements'
      preLoaderRoute: typeof OwnerAgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/owner/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/chats': {
      id: '/owner/chats'
      path: '/owner/chats'
      fullPath: '/owner/chats'
      preLoaderRoute: typeof OwnerChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/complaints': {
      id: '/owner/complaints'
      path: '/owner/complaints'
      fullPath: '/owner/complaints'
      preLoaderRoute: typeof OwnerComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/hostels': {
      id: '/owner/hostels'
      path: '/owner/hostels'
      fullPath: '/owner/hostels'
      preLoaderRoute: typeof OwnerHostelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/inquiries': {
      id: '/owner/inquiries'
      path: '/owner/inquiries'
      fullPath: '/owner/inquiries'
      preLoaderRoute: typeof OwnerInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/verification': {
      id: '/owner/verification'
      path: '/owner/verification'
      fullPath: '/owner/verification'
      preLoaderRoute: typeof OwnerVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/chats/$conversationId': {
      id: '/owner/chats/$conversationId'
      path: '/$conversationId'
      fullPath: '/owner/chats/$conversationId'
      preLoaderRoute: typeof OwnerChatsConversationIdRouteImport
      parentRoute: typeof OwnerChatsRoute
    }
  }
}

interface ChatsRouteChildren {
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsConversationIdRoute: ChatsConversationIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface OwnerChatsRouteChildren {
  OwnerChatsConversationIdRoute: typeof OwnerChatsConversationIdRoute
}

const OwnerChatsRouteChildren: OwnerChatsRouteChildren = {
  OwnerChatsConversationIdRoute: OwnerChatsConversationIdRoute,
}

const OwnerChatsRouteWithChildren = OwnerChatsRoute._addFileChildren(
  OwnerChatsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChatsRoute: ChatsRouteWithChildren,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MyAgreementsRoute: MyAgreementsRoute,
  MyBookingsRoute: MyBookingsRoute,
  MyComplaintsRoute: MyComplaintsRoute,
  MyInquiriesRoute: MyInquiriesRoute,
  NotificationsRoute: NotificationsRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  SignupRoute: SignupRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  HostelIdRoute: HostelIdRoute,
  OwnerAgreementsRoute: OwnerAgreementsRoute,
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerChatsRoute: OwnerChatsRouteWithChildren,
  OwnerComplaintsRoute: OwnerComplaintsRoute,
  OwnerHostelsRoute: OwnerHostelsRoute,
  OwnerInquiriesRoute: OwnerInquiriesRoute,
  OwnerVerificationRoute: OwnerVerificationRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
